package com.xiaomai.zhuangba;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaomai.zhuangba.data.PushNotificationDB;
import com.xiaomai.zhuangba.data.ShopCarData;
import com.xiaomai.zhuangba.data.UserInfo;

import com.xiaomai.zhuangba.PushNotificationDBDao;
import com.xiaomai.zhuangba.ShopCarDataDao;
import com.xiaomai.zhuangba.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushNotificationDBDaoConfig;
    private final DaoConfig shopCarDataDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final PushNotificationDBDao pushNotificationDBDao;
    private final ShopCarDataDao shopCarDataDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushNotificationDBDaoConfig = daoConfigMap.get(PushNotificationDBDao.class).clone();
        pushNotificationDBDaoConfig.initIdentityScope(type);

        shopCarDataDaoConfig = daoConfigMap.get(ShopCarDataDao.class).clone();
        shopCarDataDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        pushNotificationDBDao = new PushNotificationDBDao(pushNotificationDBDaoConfig, this);
        shopCarDataDao = new ShopCarDataDao(shopCarDataDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(PushNotificationDB.class, pushNotificationDBDao);
        registerDao(ShopCarData.class, shopCarDataDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        pushNotificationDBDaoConfig.clearIdentityScope();
        shopCarDataDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public PushNotificationDBDao getPushNotificationDBDao() {
        return pushNotificationDBDao;
    }

    public ShopCarDataDao getShopCarDataDao() {
        return shopCarDataDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
