package com.xiaomai.zhuangba;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xiaomai.zhuangba.data.ShopCarData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHOP_CAR_DATA".
*/
public class ShopCarDataDao extends AbstractDao<ShopCarData, Long> {

    public static final String TABLENAME = "SHOP_CAR_DATA";

    /**
     * Properties of entity ShopCarData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Money = new Property(1, String.class, "money", false, "MONEY");
        public final static Property Text = new Property(2, String.class, "text", false, "TEXT");
        public final static Property Icon = new Property(3, String.class, "icon", false, "ICON");
        public final static Property Number = new Property(4, String.class, "number", false, "NUMBER");
        public final static Property ServiceId = new Property(5, String.class, "serviceId", false, "SERVICE_ID");
        public final static Property ParentServiceId = new Property(6, String.class, "parentServiceId", false, "PARENT_SERVICE_ID");
    }


    public ShopCarDataDao(DaoConfig config) {
        super(config);
    }
    
    public ShopCarDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHOP_CAR_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MONEY\" TEXT," + // 1: money
                "\"TEXT\" TEXT," + // 2: text
                "\"ICON\" TEXT," + // 3: icon
                "\"NUMBER\" TEXT," + // 4: number
                "\"SERVICE_ID\" TEXT," + // 5: serviceId
                "\"PARENT_SERVICE_ID\" TEXT);"); // 6: parentServiceId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHOP_CAR_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShopCarData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(2, money);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(4, icon);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
 
        String serviceId = entity.getServiceId();
        if (serviceId != null) {
            stmt.bindString(6, serviceId);
        }
 
        String parentServiceId = entity.getParentServiceId();
        if (parentServiceId != null) {
            stmt.bindString(7, parentServiceId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShopCarData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String money = entity.getMoney();
        if (money != null) {
            stmt.bindString(2, money);
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(3, text);
        }
 
        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(4, icon);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
 
        String serviceId = entity.getServiceId();
        if (serviceId != null) {
            stmt.bindString(6, serviceId);
        }
 
        String parentServiceId = entity.getParentServiceId();
        if (parentServiceId != null) {
            stmt.bindString(7, parentServiceId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ShopCarData readEntity(Cursor cursor, int offset) {
        ShopCarData entity = new ShopCarData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // money
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // text
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // icon
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // number
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // serviceId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // parentServiceId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShopCarData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMoney(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIcon(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNumber(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setServiceId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setParentServiceId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShopCarData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShopCarData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShopCarData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
